# Generated by Django 6.0.3 on 2026-03-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahalla',
            name='district',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
