# Generated by Django 6.0.3 on 2026-03-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0002_alter_mahalla_district"),
    ]

    operations = [
        migrations.AddField(
            model_name="mahalla",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
