# Generated by Django 6.0.3 on 2026-03-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("references", "0003_mahalla_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mahalla",
            name="is_active",
        ),
        migrations.AddField(
            model_name="service",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
