# Generated by Django 6.0.3 on 2026-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_remove_mahalla_is_active_service_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationtype',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='mahalla',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-pk']},
        ),
    ]
