# Generated by Django 6.0.3 on 2026-07-08 04:30

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('references', '0005_alter_applicationtype_options_alter_mahalla_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_medium', models.CharField()),
                ('full_name', models.CharField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('text', models.TextField()),
                ('mahalla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.mahalla', unique=True)),
            ],
        ),
    ]
