# Generated by Django 6.0.3 on 2026-07-08 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicant'),
        ('references', '0005_alter_applicationtype_options_alter_mahalla_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='age_medium',
            field=models.CharField(choices=[('30_plus', '30 yoshdan katta'), ('30_minus', '30 yoshdan kichik')], default='30_minus', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='mahalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.mahalla'),
        ),
    ]
