# Generated by Django 6.0.3 on 2026-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_applicant_age_medium_alter_applicant_mahalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='telegram_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
