# Generated by Django 6.0.3 on 2026-07-08 07:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_applicant_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='response',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
