# Generated by Django 6.0.3 on 2026-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-pk'], 'verbose_name': 'Accountlar'},
        ),
    ]
