# Generated by Django 6.0.3 on 2026-04-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('references', '0005_alter_applicationtype_options_alter_mahalla_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'super_admin')), fields=('role',), name='unique_super_admin'),
        ),
    ]
