# Generated by Django 6.0.3 on 2026-07-08 08:21

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_applicant_response_alter_applicant_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='app_number',
            field=models.CharField(default=apps.accounts.models.generate_app_number),
        ),
    ]
