# Generated by Django 6.0.3 on 2026-03-15 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0001_initial"),
        ("references", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["-created_at"], "verbose_name": "Arizalar"},
        ),
        migrations.AlterField(
            model_name="application",
            name="address_text",
            field=models.CharField(max_length=500, verbose_name="Ko'cha va uy raqami"),
        ),
        migrations.AlterField(
            model_name="application",
            name="app_number",
            field=models.CharField(
                max_length=30, unique=True, verbose_name="Ariza raqami"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="app_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="references.applicationtype",
                verbose_name="Murojaat turi",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="citizen_name",
            field=models.CharField(max_length=200, verbose_name="Fuqaro F.I.O."),
        ),
        migrations.AlterField(
            model_name="application",
            name="citizen_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon (ixtiyoriy)"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Yopilgan vaqt"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="content",
            field=models.TextField(verbose_name="Murojat"),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Kim kiritgani"),
        ),
        migrations.AlterField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kim ko'rib chiqqani (hokim)",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Yangi"),
                    ("in_review", "Ko‘rib chiqilmoqda"),
                    ("sent_to_mahalla", "Mahallaga yuborildi"),
                    ("acknowledged", "Qabul qilindi"),
                    ("inspected", "Tekshirildi"),
                    ("closed", "Yopildi"),
                    ("archived", "Arxivlandi"),
                    ("reopened", "Qayta ochildi"),
                ],
                default="new",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="mahallareport",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("acknowledged", "Qabul qilindi"),
                    ("inspected", "Tekshirildi"),
                    ("commented", "Izoh qoldirildi"),
                ],
                default="acknowledged",
                max_length=20,
            ),
        ),
    ]
