# Generated by Django 6.0.3 on 2026-04-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_alter_application_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='mahallareport',
            options={'ordering': ['-pk']},
        ),
    ]
