# Generated by Django 6.0.3 on 2026-04-24 18:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_alter_application_status'),
        ('references', '0005_alter_applicationtype_options_alter_mahalla_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_c6d08d_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['closed_at'], name='application_closed__9c8088_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['service'], name='application_service_3562c2_idx'),
        ),
    ]
