# Generated by Django 6.0.3 on 2026-07-08 05:43

import apps.applications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_application_application_created_c6d08d_idx_and_more'),
        ('references', '0005_alter_applicationtype_options_alter_mahalla_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='age_medium',
            field=models.CharField(choices=[('30_plus', '30 yoshdan katta'), ('30_minus', '30 yoshdan kichik')], default='30_minus', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='address_text',
            field=models.CharField(max_length=500, null=True, verbose_name="Ko'cha va uy raqami"),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_number',
            field=models.CharField(default=apps.applications.models.generate_app_number, max_length=30, unique=True, verbose_name='Ariza raqami'),
        ),
        migrations.AlterField(
            model_name='application',
            name='app_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='references.applicationtype', verbose_name='Murojaat turi'),
        ),
        migrations.AlterField(
            model_name='application',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='references.service'),
        ),
    ]
