# Generated by Django 6.0.3 on 2026-07-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_application_age_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
