# Generated by Django 6.0.3 on 2026-07-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='age_medium',
        ),
        migrations.RemoveField(
            model_name='application',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('in_review', "Hokim ko'rdi"), ('sent_to_mahalla', 'Mahallaga yuborildi'), ('acknowledged', "Oqsoqol ko'rdi"), ('inspected', 'Tekshirildi'), ('closed', 'Yopildi'), ('archived', 'Arxivlandi'), ('reopened', 'Qayta ochildi')], default='new', max_length=30),
        ),
    ]
