# Generated by Django 6.0.3 on 2026-03-24 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_mahallareport_action_type'),
        ('audit', '0004_remove_auditlog_aplications_auditlog_application_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_entity__9535bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_applica_a2c757_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_audit_created_2c1626_idx',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='aplications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.application'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='application',
        ),
    ]
