# Generated by Django 6.0.3 on 2026-03-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_alter_mahallareport_action_type"),
        ("audit", "0006_rename_aplications_auditlog_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="applications.application",
            ),
        ),
    ]
